//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentElection.PostgreSQL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditLog
    {
        public int Id { get; set; }
        public string TableName { get; set; }
        public int Action { get; set; }
        public System.DateTime OccuredAt { get; set; }
        public string RowData { get; set; }
        public string ChangedFields { get; set; }
        public int UserId { get; set; }
    
        public virtual User User { get; set; }
    }
}
